% Plot for CDC paper
close all

% Plot made for cdc paper
% not sure what R was


learned_steps = [10.84,9.51,5.73,2.6]';
greedy_steps = [7.95,6.45,4.46,2.6]';
agents = [4,3,2,1];

nS = [164025,11664,5625,100]';

hold on;

learned = plot(agents,learned_steps,'k--','LineWidth',2);
greedy = plot(agents,greedy_steps,'b--','LineWidth',2);
hTitle = title('Two-agent, multiple task simulation');
hXLabel = xlabel('Number of Tasks');
hYLabel = ylabel('Steps to episode completion');
hLegend = legend('Learned policy','Greedy policy','location', 'NorthWest' );
xlim([.5,4.5])
ylim([2,12])

set(learned,'Marker','s','MarkerFaceColor',[.75 .75 1],'MarkerSize',10)
set(greedy,'LineStyle','--','LineWidth',2,'Marker','o','MarkerFaceColor',[.75 .75 1],'MarkerSize',10)


set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([hTitle, hXLabel, hYLabel], ...
    'FontName'   , 'AvantGarde');
set([hLegend, gca]             , ...
    'FontSize'   , 10           );
set([hXLabel, hYLabel]  , ...
    'FontSize'   , 10          ,...
    'FontWeight' , 'normal'      );
set( hTitle                    , ...
    'FontSize'   , 12          , ...
    'FontWeight' , 'normal'      );


set(gca, ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'off'      , ...
  'YMinorTick'  , 'off'      , ...
  'YGrid'       , 'on'      , ...
  'XGrid'       , 'on'      ,...
  'XTick'       ,1:4        ,...
  'LineWidth'   , 1         );